                                                                           WEEKEND ACADEMY WEEK2

In [37]:
print("Hello world")

Hello world


In [4]:
sum = ()
for i in range (11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
##While loop
## Continues running the program provided the statememnt is true

In [26]:
i=0
sum=0
#print(sum)
while(i<=10):
     sum = sum+i
     print(i)
     i=i+1
print(sum)

0
1
2
3
4
5
6
7
8
9
10
55


In [29]:
##Lists
## This is a ordered collection of items and they can be of different types

In [30]:
mathogothanio = ["Mango", 36, "Mwende"]
print(mathogothanio)

['Mango', 36, 'Mwende']


In [31]:
mathogothanio[0]

'Mango'

In [33]:
mathogothanio[1]

36

In [36]:
mathogothanio.append("Muia")
print(mathogothanio)

['Mango', 36, 'Mwende', 'Muia', 'Muia', 'Muia']


In [41]:
mathogothanio.remove("Muia")
print(mathogothanio)

['Mango', 36, 'Mwende']


In [ ]:
#Dictionaries
## its used to create unordered collection of key value pair

In [65]:
person = {"Name":"Mercy", "Age":10 ,"Country":"Kenya"}
for k, v in person.items():
   print(k, ":" , v)


Name : Mercy
Age : 10
Country : Kenya


In [44]:

import pandas as pd

weather ={
    "dates": ['1/3/2025', '2/3/2025','3/3/2025', '4/3/2025','5/3/2025', '6/3/2025', '7/3/2025'],
    "windspeed": ['23' , '24' ,'23' ,'45' ,'21' , '23' , '21'],
    "TypaDay": ['windy', 'sunny', 'calm', 'sunny' ,'sunny', 'calm','Rainy'],
}
df = pd.DataFrame(weather)

In [45]:
df

dates windspeed TypaDay
0  1/3/2025        23   windy
1  2/3/2025        24   sunny
2  3/3/2025        23    calm
3  4/3/2025        45   sunny
4  5/3/2025        21   sunny
5  6/3/2025        23    calm
6  7/3/2025        21   Rainy

##Arrays
##They are used to store homogeneous data types ie same datatypes. provided by numpy module
To use arrays you must import numpy. initialize the array as follows 

In [3]:
import array
results= array.array("i", [70, 40, 60,])

for i in results:
    print(i)
#

70
40
60


In [4]:
import numpy as np
myarray = np.array(["Mercy", "Muia", "Felix"])
array2 = np.array([10, 15, 67,89])

for i in array2, myarray:
    print(i)

[10 15 67 89]
['Mercy' 'Muia' 'Felix']


Machine Learning Are computer programmes are used to recognise patterns in data or make predictions
   Categorised into:
                    -Supervised , Unsupervised, Semi-supervised, Reinforcement learning
   
Supervised- Are models trained using labeled data, input is targed to collect output
            Learning a mapping from input to output making it possible to predict new data
            Can either be Regression or Classification 
            ----Classification - (Takes dicrete values) yes and no eg Diabetic or Not Diabetic
            ----Regression - (takes contious) eg sales

Classification- KNN, Decision Tree, support Vector Machine (SVM)
Regression - Linear Regression, Random Forest, K- nearest Neighbour(kNN), Neural Neteork

In [9]:
import pandas as pd
HouseData = {
    "House size":[1500, 4000, 2000, 1800],
    "Number of rooms":[2, 4, 2, 3],
    "House price" :[20000, 30000, 40000, 2100],
}
df= pd.DataFrame(HouseData)
df

House size  Number of rooms  House price
0        1500                2        20000
1        4000                4        30000
2        2000                2        40000
3        1800                3         2100

In [13]:
import numpy as np

House_size = np.array ([1500, 4000, 2000, 1800])
Number_of_rooms = ([2, 4, 2, 3])
House_price= ([20000, 30000, 40000, 2100])


In [15]:
x= np.column_stack((House_size, Number_of_rooms))
y = House_price

In [17]:
print(x)
print(y)

[[1500    2]
 [4000    4]
 [2000    2]
 [1800    3]]
[20000, 30000, 40000, 2100]


In [19]:
for i in x, y:
    print(i)

[[1500    2]
 [4000    4]
 [2000    2]
 [1800    3]]
[20000, 30000, 40000, 2100]


In [23]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x, y)

LinearRegression()

In [30]:
print(" Y intercept:, ", model.intercept_)

 Y intercept:,  43886.064030131805


In [29]:
print("My coeficient is ", model.coef_)

My coeficient is  [ 2.77721281e+01 -3.10659134e+04]


                                                          PREDICTION

In [33]:
newhouse = ([[600, 5]])
price = model.predict(newhouse)
print("My new house price ", price)

My new house price  [-94780.2259887]
